 # 1.list 和array

In [19]:
import numpy as np
import pandas as pd
nums = [1.2, 3.4, 5.6]
a = np.array(nums)
nums * 2

[1.2, 3.4, 5.6, 1.2, 3.4, 5.6]

list格式有逗号 *2之后复制

In [20]:
a * 2

array([ 2.4,  6.8, 11.2])

In [21]:
print(a.shape, a.dtype, a.ndim)

(3,) float64 1


In [24]:
print(a.ndim)

1


维度是1

In [25]:
df = pd.read_csv('pandas/data/titanic.csv')
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [23]:
s = df["Age"].to_numpy()      # ← 脱壳：Series 变成 ndarray

In [28]:
print(df.shape)   

(891, 12)


In [29]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [30]:
print(s.shape, s.dtype)

(891,) float64


In [31]:
arr = df.to_numpy()

In [32]:
print(arr.shape, arr.dtype)

(891, 12) object


# 2.Day2

In [33]:
t = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(t)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
print("t[0]    ->", t[0])

t[0]    -> [1 2 3]


In [36]:
print("t[:, 0] ->", t[:, 0])

t[:, 0] -> [1 4 7]


In [45]:
print("t[0,0]    ->", t[0,0])

t[0,0]    -> 1


In [46]:
print(t[0:2, 1:3])

[[2 3]
 [5 6]]


In [47]:
print(t > 5)

[[False False False]
 [False False  True]
 [ True  True  True]]


打出来都是bool值

In [48]:
print(t[t > 5])

[6 7 8 9]


In [49]:
m = t[:, 0] > 4     # 先看这张真假表长什么样
print(m)
print(t[m])         # 再拿它当筛子

[False False  True]
[[7 8 9]]


表里必须所有数都大于4才是true

In [50]:
u = np.array([[9, 1, 1],
              [2, 2, 2],
              [3, 3, 3]])

print("u[:, 0]        ->", u[:, 0])
print("u[:, 0] > 4    ->", u[:, 0] > 4)
print("u[u[:, 0] > 4] ->", u[u[:, 0] > 4])

u[:, 0]        -> [9 2 3]
u[:, 0] > 4    -> [ True False False]
u[u[:, 0] > 4] -> [[9 1 1]]


In [51]:
print(df[df["Age"] > 30].shape)     # pandas 写法 —— 你早就会的那个

s = df["Age"].to_numpy()
print(s[s > 30].shape)              # numpy 写法 —— 自己动手做同一件事

(305, 12)
(305,)


今天拿下的五个写法：

写法	挑走什么	结果
t[:, 0]	第一列	一维 (3,)
t[0, 0]	第一行第一列那一个数	一个数
t[0:2, 1:3]	行01 × 列12 的一块（含头不含尾）	二维 (2, 2)
t[t > 5]	筛子跟表同形 → 挑格子	压平成 (4,)
t[m] / s[m] / df[m]	筛子比被筛的少一维 → 挑整行	整行原样搬走


## 3day3 广播

##  1最常见的撑法

In [3]:
import numpy as np

In [6]:
t= np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.array([10,20,30])

In [7]:
print(t+v)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


竖着加的

In [9]:
c = np.array([[10],
              [20],
              [30]])
print(t + c)

[[11 12 13]
 [24 25 26]
 [37 38 39]]


匹配不上

In [11]:
w = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])    # 形状 (3,4)
x = np.array([100, 200, 300])      # 形状 (3,)

print(w + x)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [12]:
y = np.array([100, 200, 300, 400])   # 形状 (4,)
print(w + y)

[[101 202 303 404]
 [105 206 307 408]
 [109 210 311 412]]


In [14]:
print(x[:, np.newaxis].shape)     # x[:, np.newaxis] 和 x[:, None]等价
print(w + x[:, None])

(3, 1)
[[101 102 103 104]
 [205 206 207 208]
 [309 310 311 312]]


In [23]:
import pandas as pd
print(np.array(1.1).shape)   # 标量长什么样：()

df = pd.read_csv('pandas/data/titanic.csv')
fare = df["Fare"]

()


In [25]:
print(fare.shape)            # (891,)
print((fare * 1.1))   # 每张票价涨 10%

(891,)
0       7.97500
1      78.41163
2       8.71750
3      58.41000
4       8.85500
         ...   
886    14.30000
887    33.00000
888    25.79500
889    33.00000
890     8.52500
Name: Fare, Length: 891, dtype: float64
